### ISSUE TITLE
Android inline autofill

### ISSUE THREAD

**Issue by w0ken** [bitwarden/mobile#1156]
## Describe the Bug

The login information doesn't show up on Gboard's suggestion strip.

## Steps To Reproduce

1. Have the latest available versions of all the apps (Bitwarden, Bromite, Element, Firefox, Fennec Firefox, Gboard, Vanadium, etc. ).
2. Open the website/app you wish to log in to.
3. Tap on either the username (or password) login field.

## Expected Result

Login information should be on the suggestion bar.

## Actual Result

Suggestion strip shows he default items, the ones that are present when typing in other apps.
Clearing data, reinstalling, using different app settings in both Bitwarden and Gboard or rebooting device don't solve the issue.

## Screenshots or Videos

https://i.imgur.com/4xubTvg.png

## Environment

- Device:Pixel 3a
- Operating system: Android 11 (Graphene OS)
- Build Version: 2.7.0 (3258)
- Is this a Beta release? N

**Comment by mportune-bw** [comment]
Hi @w0ken , I've compared your log with a device where the inline presentation is working.  There are two events that are missing from yours, though they may have just been excluded from your paste so it may be worth checking again..  (This is with the latest GBoard and Chrome running on a Pixel 4a with factory ROM)

```
2020-11-21 17:25:16.946 3259-3259/? V/InlinePresentationRendererServiceImpl: onRenderSuggestion: width=-2, height=-2
2020-11-21 17:25:16.950 3259-3259/? V/InlineSuggestionRenderService: width=-2, height=-2, measuredSize=594x121
```

Since your screenshot shows the default popup showing, that could mean one of two things:

1) "Use Inline Autofill" is disabled in Bitwarden's autofill settings, or
2) Some part of the dependency chain for inline presentations has failed resulting in a fallback to the popup (IME failed to provide inline suggestion, ROM failed to transfer inline suggestion to us, we failed to create inline request, or ROM failed to deliver our inline request back to the IME).

Graphene OS is the unknown here.  I would suggest testing with another app that uses inline autofill to see if it works, then we'll go from there.

**Comment by w0ken** [comment]
The inline option is enabled. I also tried with the accessibility popup option disabled. Still didn't work.
I'm trying to find another app that provides inline autofill but google search isn't helping much. In the meantime, here's a bigger logcat.
 https://controlc.com/e997438b/fullscreen.php?hash=00d9421d2a9f1184b7470773f09853c6&toolbar=true&linenum=true

**Comment by heiserhorn** [comment]
Hi, I am experiencing the same problem Pixel 4, Android 11, gboard and firefox everything up to date. The inline suggestion is not proposed for all sites. Moreover in some apps I do not have the inline suggestion nor the pop-up (for example with the disney + app). Happy to provide more details.

**Comment by simonkotwicz** [comment]
I'm seeing the inline autofill stop working/showing up after a while (it usually show `bitwarden vault locked` on the inline autofill when working). A restart of the device or disable/re-enable of inline autofill for Bitwarden fixes it.

**Comment by heiserhorn** [comment]
I did some extra testing. The inline autofill is provided when using Chrome and not with Firefox on some specific sites. If interested one of the sites I am having the issue is hockeymanager.ch/login.

Firefox version is 83.1.0, Bitwarden 2.7.0, Gboard 10.0.02.338070508-release-arm64-v8a

For the disney + app version is 1.11.2 (in this app I do not have the popup neither the inline).

**Comment by hakkikaancaliskan** [comment]
I have absolutely same problem with @heiserhorn.
Xperia XZ1 Lineageos 18 Android 11
Latest firefox beta(84.0.0-beta.4)
Latest gboard(sürüm 10.0.02.338070508-release-arm64-v8a)

I can provide logs if you guys want.

**Comment by sevesalm** [comment]
I also have problems using Inline Autofill on Android 11. I have it enabled on Bitwarden settings, I'm using gboard on Chrome. Usually the autofill works immediately when I open Chrome but fails later on the same site. Failure here means I don't get any entries in the suggestion strip. Closing and reopening Chrome usually helps.

Currently autofill is basically unusable and unreliable. I don't know what is causing this issue: Bitwarden or some other component/app.

Bitwarden 2.7.0 (3258)
Chrome 87.0.4280.101
gBoard 10.0.02.338070508-release-amd64-v8a
Android 11/Samsung OneUI 3.0.

I'll provide more info if it helps.

**Comment by johns2s** [comment]
> I also have problems using Inline Autofill on Android 11. I have it enabled on Bitwarden settings, I'm using gboard on Chrome. Usually the autofill works immediately when I open Chrome but fails later on the same site. Failure here means I don't get any entries in the suggestion strip. Closing and reopening Chrome usually helps.
> 
> Currently autofill is basically unusable and unreliable. I don't know what is causing this issue: Bitwarden or some other component/app.
> 
> Bitwarden 2.7.0 (3258)
> Premium account
> Chrome 87.0.4280.101
> gBoard 10.0.02.338070508-release-amd64-v8a
> Android 11/Samsung OneUI 3.0.
> 
> I'll provide more info if it helps.

There was an issue on Chrome's end that is fixed in Chrome Dev and Chrome Canary.

**Comment by sevesalm** [comment]
> There was an issue on Chrome's end that is fixed in Chrome Dev and Chrome Canary.

Ok! Could it be related to my case also? So it is broken on Chrome 87 but fixed on 89? Do you happen to have a link to the issue or fix?

I tested a bit more. On Android Firefox the inline autofill works a lot better. Still not 100% reliable (sometimes no autofill option is offered at all) but a lot better than on Chrome.

**Comment by johns2s** [comment]
> > There was an issue on Chrome's end that is fixed in Chrome Dev and Chrome Canary.
> 
> Ok! Could it be related to my case also? So it is broken on Chrome 87 but fixed on 89? Do you happen to have a link to the issue or fix?
> 
> I tested a bit more. On Android Firefox the inline autofill works a lot better. Still not 100% reliable (sometimes no autofill option is offered at all) but a lot better than on Chrome.

https://github.com/bitwarden/mobile/issues/489#issuecomment-736736959

**Comment by bingoxo** [comment]
Has anyone tried if it works with OpenBoard ,FlorisBoard ,AnySoftKeyboard or any other FOSS keyboard ?

**Comment by Jannomag** [comment]
Hi,
I'm having similar issues using Gboard 10.2.02.351353117 beta and Microsoft Edge 45.12.4.5125.
Sometimes it's working once or twice until it stops working. Then I need to reenable the autofill service though bitwardens settings.

Samsung Galaxy S10 with OneUI 3.0 (Android 11).

**Comment by heiserhorn** [comment]
Quick update on this one: with the latest FF nightly the behavior has improved but still not reliable 100%

**Comment by escape0707** [comment]
Can't use autofill for latest telegram 7.4.2 with bitwarden 2.8.0 and Pixel Experience 11. Weird. Although websites in firefox, AnkiDroid etc is working.

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
