### ISSUE TITLE
Login resets to beginning or crashes on Yubikey/keyboard plug in/out at 2FA screen

### ISSUE THREAD

**Issue by bradfa** [bitwarden/mobile#350]
When trying to log in on Android, when plugging in a Yubikey or a standard keyboard via USB as a 2FA device at the 2FA screen, the app will return to the beginning of the login process or crash entirely.  This makes using a Yubikey via USB impossible unless you insert it prior to opening the Bitwarden app to start the login process.

The app appears to crash if I wipe all the app's data from the device and then try to log in, plugging my Yubikey in at the 2FA screen.  The app appears to go back to the start page of the login process when plugging my Yubikey in at the 2FA screen if I've already once successfully logged in.  I'm unsure why there's a difference here, cached or saved data locally matters?

My testing has been on an LG G5 model RS988 running Android 7.0, a Yubikey NEO via USB, and Bitwarden version 1.17.1 from the Play store.

**Comment by kspearrin** [comment]
Unfortunately I don't have an Android device with a USB port on it at this time, so I can't reproduce the issue. I'll see if there is anything in the crash logs.

**Comment by kspearrin** [comment]
Could you give me an approx timestamp on a crash (make sure you open the app again after the crash so that the report can be uploaded)?

**Comment by bradfa** [comment]
@kspearrin I reproduced it while writing up this issue, so some time just prior to 12:54pm EDT today was when I experienced the "crashes" (in quotes because the app exited but I'm not entirely sure why, it seemed like a crash to me).
In testing right now, I'm now unable to reproduce the crash but I still can reproduce the "return to the beginning of the login process" failure mode.

**Comment by bradfa** [comment]
@kspearrin just had it crash again just now, 3pm EDT.

**Comment by kspearrin** [comment]
Ok, thanks. I found the crash log:

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Java.Lang.IllegalStateException: Foreground dispatch can only be enabled when your activity is resumed
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e44be0cdd50d455da1e7c0f6bc4979bf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <fd47eb562139466c9c630be6613ec122>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <fd47eb562139466c9c630be6613ec122>:0 
  at Android.Nfc.NfcAdapter.EnableForegroundDispatch (Android.App.Activity activity, Android.App.PendingIntent intent, Android.Content.IntentFilter[] filters, System.String[][] techLists) [0x0008e] in <528ad9ae001340cd9cd464d42d836a06>:0 
  at Bit.Android.MainActivity.ListenYubiKey (System.Boolean listen) [0x00068] in <add3e379c4594eac8d5b6b8d5461e2e8>:0 
  at Bit.Android.MainActivity.<OnCreate>b__7_0 (Xamarin.Forms.Application sender, System.Boolean listen) [0x00000] in <add3e379c4594eac8d5b6b8d5461e2e8>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <e44be0cdd50d455da1e7c0f6bc4979bf>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0004b] in <e44be0cdd50d455da1e7c0f6bc4979bf>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <e44be0cdd50d455da1e7c0f6bc4979bf>:0 
  at Xamarin.Forms.MessagingCenter+Subscription.InvokeCallback (System.Object sender, System.Object args) [0x00076] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args) [0x0006b] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00013] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.MessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00005] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Bit.App.Pages.LoginTwoFactorPage.ListenYubiKey (System.Boolean listen, System.Boolean overrideCheck) [0x00026] in <c121207d583c4169bad14f6f352eb197>:0 
  at Bit.App.Pages.LoginTwoFactorPage.OnAppearing () [0x00006] in <c121207d583c4169bad14f6f352eb197>:0 
  at Xamarin.Forms.Page.SendAppearing () [0x00024] in <1aabc0fecdaa41b6a5c04760c77bb648>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.set_UserVisibleHint (System.Boolean value) [0x0004a] in <aae4e9ce5a5b4d3eaec4edf21079f3fa>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer+<>c__DisplayClass62_0.<SwitchContentAsync>b__0 () [0x0000d] in <aae4e9ce5a5b4d3eaec4edf21079f3fa>:0 
  at Xamarin.Forms.Forms+AndroidPlatformServices+<>c__DisplayClass23_0.<StartTimer>b__0 () [0x00000] in <aae4e9ce5a5b4d3eaec4edf21079f3fa>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <528ad9ae001340cd9cd464d42d836a06>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <528ad9ae001340cd9cd464d42d836a06>:0 
  at (wrapper dynamic-method) System.Object.bc1ed743-3c60-418f-b831-1c9301b37169(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by kspearrin** [comment]
Does this device have NFC enabled?

**Comment by bradfa** [comment]
In the 3pm crash yes. In the earlier crashes I'm not sure if I had NFC on
or not.

>

**Comment by kspearrin** [comment]
Can you try disabling NFC on the device completely and see if you can reproduce the crash when that off?

**Comment by bradfa** [comment]
If I disable NFC I can't get the crash to happen.  With NFC disabled when I insert a USB keyboard or Yubikey during the 2FA entry page it just takes me back to the login start page.

With NFC enabled, I created the crash by inserting a USB Yubikey at 3:31 pm EDT.  I then reopened the app and logged in, so hopefully you can find the crash report.  It seems that NFC being enabled is required to make the crash happen.

**Comment by kspearrin** [comment]
Ok, I think the keyboard keys that the yubikey is simulating is causing the "back button" event to happen. This is why you get taken back to the login page. This is also causing it to crash when NFC is enabled because the NFC adapter/listener is not properly disconnected on back button events.

**Comment by bradfa** [comment]
@kspearrin the "back button event" happens with a Dell USB keyboard, too, it's not just my Yubikey that does it.

Thanks for being so responsive :+1:

**Comment by kspearrin** [comment]
Its probably something to do with whatever event occurs whenever you plug in a USB device. I am not sure what that is

**Comment by bradfa** [comment]
@kspearrin the work around is to plug in the USB keyboard or Yubikey before starting to try and login to Bitwarden, then everything works fine with NFC on or off.  So it's not urgent to fix this I don't think.  Sorry I'm not that familiar with Xamarin (or even Java in general) so I'm not sure how much help I can be in debugging, sorry :(

**Comment by kspearrin** [comment]
On the home, click "Create Account". Then plug in the device. Does it take you back to home screen there too?

**Comment by bradfa** [comment]
Yes.  In "Create Account" if I plug in the Yubikey with NFC disabled it goes back to the home screen.

**Comment by kspearrin** [comment]
Ok, that proves my theory then. Connecting a USB device is triggering the back event for some reason.

**Comment by kspearrin** [comment]
Can you try updating to the beta to see if the same issue still occurs with the back button? https://play.google.com/apps/testing/com.x8bit.bitwarden

**Comment by bradfa** [comment]
On 1.17.2 (1480) "beta" release from the Play store, I still get the crash when inserting Yubikey via USB when NFC is enabled.  Crash at approximately 7:39am EDT.

**Comment by bradfa** [comment]
On 1.17.2 (1480) "beta" release from the Play store, the back button action still seems to occur when inserting Yubikey via USB when NFC is *disabled*.

**Comment by kspearrin** [comment]
I pushed build 1490 to the beta track on google play. This build prevents the back button action on the yubikey page. Can you give it a try and see if it works with 1490?

**Comment by bradfa** [comment]
With build 1490, inserting my Yubikey via USB at the 2FA screen still results in the back operation happening with NFC off.  Also, with NFC on and trying to use my Yubikey NEO via NFC for 2FA, after verifying the Yubikey the app crashes although the login seems to succeed as opening the app again requests only my master password to unlock my vault.  Crash for this was at approximately 10:34am EDT today.

**Comment by kspearrin** [comment]
Can you try again on 1491? Sorry, I don't have any other way to test this since my device doesn't have a USB port for a YubiKey

**Comment by bradfa** [comment]
With 1491 the "back" action still seems to happen when inserting a Yubikey via USB at the 2FA screen when NFC is disabled.
With 1491 the crash still happens when inserting a Yubikey via USB at the 2FA screen when NFC is enabled.  Crash at 11:51am EDT.

**Comment by bradfa** [comment]
Just to give a quick update, on build 1495 the crash still happens the same way.  Crash at approximately 7:50 am EDT today if you need the logs.

**Comment by kspearrin** [comment]
Thanks. Unfortunately I don't have a good solution for this at this time.

**Comment by eliykat** [comment]
Fixed by #1246
