### ISSUE TITLE
Password vault not syncing at every login

### ISSUE THREAD

**Issue by pavankjadda** [bitwarden/mobile#457]
Whenever I add/update a password on a Laptop or Desktop, it’s not automatically syncing to my iPhone even though I authenticate my phone with FaceId. Push notifications are enabled to the app.
I am using iOS 12 on iPhone X

**Comment by chewiesGit** [comment]
I noticed the same thing using Android 8.0.0 on a LG G7. I often have to manually sync first to have all new passwords.

This also leads to the problem that when deauthorizing all sessions in the web vault, the active session on my mobile does not get deauthorized immediately. I first need to do something that triggers communication with the server (like manually syncing) that I get logged out. Would be nice if deauthorizing would lead to logging out immediately.

**Comment by m3gg3** [comment]
Same Problem Herr, please give us an option to enable sync on every app start and Everytime autofill is searching the vault

**Comment by dpbrick** [comment]
No solution after 4 months?  What is going on. Are you folks not supporting Bitwarden anymore?  That would be a shame because it has so much promise. Do we need to pay to get support?  If so, I will, because I think this is far superior to LastPass, or at least it could be if you get the glitches worked out.

**Comment by dpbrick** [comment]
Actually found that by deleting the app, redownloading it from the cloud, installing and logging in, the bug was fixed — at least temporarily. One of the first things that happens when you log in is it asks you to accept notifications in order to enable AUTOMATIC VAULT SYNCHRONIZATION. When I allowed notifications, BANG! All my recently added logins appeared. The app must have gotten out of whack somehow because I know I never turned notifications off for it.

**Comment by haldyr** [comment]
Same problem on Android 8.

**Comment by LapinFou** [comment]
Hi folks,

First of all, I would like to congratulate the dev team for this fantastic password manager. 👍 
Like many people I trust more the open source projects than the proprietary ones. This is the only way to be 100% sure that there is not backdoor and that there is critical issue in the security.

Back to this issue: I'm running the latest apps on my Win laptop (Win10 Home & Pro), my android Tablet (Android v9) and my iPhone 7 (iOS 12.3.1).

Like some users, I got an issue with the iOS iPhone app (v2.1.2 build 53).
- When adding/updating one or more items on the iPhone, the modifications are instantaneously **push** to the vault and available for all others clients.
- When adding/updating one or more items from the vault website, the modifications are not **pull** to the iPhone Apps. For all others clients (Win stand alone app & Firefox addon), it is OK. The modifications are instantaneously visible.
- When adding/updating one or more items from a stand-alone or addon app,  the modifications are instantaneously **pull** to others Apps, excepted for the iOS iPhone app...

In my case, the **pull** mechanism is not working as expected. I need to manually force the vault synchronization.

**Comment by kspearrin** [comment]
@LapinFou What if you reinstall the mobile app? Does it work then?

**Comment by LapinFou** [comment]
I already try (without rebooting my iPhone), unfortunately this didn't solve the problem.
Do I need to clear something after uninstalling the app?

**Comment by kspearrin** [comment]
@LapinFou Are you using Bitwarden Cloud or On-prem hosted?

**Comment by LapinFou** [comment]
At first, I tried the On-prem solution, but I decided that Bitwarden could be fully trusted, so I switched on the Cloud version with the Premium subscription.

**Comment by LapinFou** [comment]
I forgot to mention that this issue is still the same using TouchID or with typing the master passwd.

**Comment by kspearrin** [comment]
After you reinstalled, did you get prompted to accept push notifications upon logging back in?

**Comment by LapinFou** [comment]
Yes, the push notification windows pop-up just after the reinstallation.
And, off course, I accepted it.

**Comment by kspearrin** [comment]
Unfortunately, I am still not able to reproduce the issue. WE'll have to keep looking.

**Comment by LapinFou** [comment]
This is the worst kind of bug. 90% of the job is to be able to reproduce it on demand.
Don't hesitate to contact me if I can help you in anyway.

**Comment by LapinFou** [comment]
If this can be any helpful, from my iPhone, the modifications are immediately push on the vault. However the sync date & time is not updated ont the iOS app.

**Comment by kspearrin** [comment]
@LapinFou That is the expected functionality. The timestamp you see under Settings > Sync is the last time a full sync has occurred, not an incremental sync like when modifying a single item.

**Comment by LapinFou** [comment]
OK. Got it. Thanks for the information.

**Comment by LapinFou** [comment]
After upgrading to iOS 12.4, it looks like it was working better, but finally not 😢 
Here is a procedure which I can reproduce on my iPhone.

- Open the BitWander app on the iPhone and open it with the Touch ID.
- Lock the iPhone.
- From a client, add an item.
- Unlock the iPhone → the new added item is available.
- Closed the iOS app, then lock the iPhone.
- From a client, remove the newly added item.
- Unlock the iPhone, then launch the apps. Unlock it with TouchID.
- The sync is broken, the remove item is still present.
- Add a 2nd item from the iPhone. It will be added on the vault, by the 1st deleted item is still present.

I hope this can help.

**Comment by LapinFou** [comment]
As a workaround, it could be nice to force a synchronization when holding and sweeping the finger to the bottom. Same gesture than for the iOS mail app.

**Comment by kspearrin** [comment]
@LapinFou I tried these steps and wasn't able to reproduce. All actions synced via push notification. Will have to continue to investigate.

**Comment by LapinFou** [comment]
Damn it... 😞 
I guess your tried several times?

I tried again few minutes ago, and I can reproduce the issue following the procedure described above.
I tried with my iPhone connected to the WiFi and only connected to the 4G network. Same behavior.
This bug is really a nightmare...

For sure, there is something which is consistent. As long the BitWarden app is opened, the sync is working.
As soon as the BitWarden iOS app is closed, it will not resync properly the next time the app is launched if some items have been added or deleted from another client.

**Comment by lumpycustard** [comment]
Just wanted to chime in and report i'm having the same issue on iOS and an iPhone XS.

Something that i've noticed that hasn't been mentioned here though:

1. Started a new job, set up Bitwarden on my work laptop.
2. Saved several passwords within Bitwarden, everything seemed to be syncing properly.
3. Was given a temporary computer to use in the training room, and needed to log into an account, so i opened bitwarden on my iPhone.... the password that i was looking for was not synced.
4. Dragged the page down several times hoping Bitwarden would sync... no bueno, password still missing.
5. Installed Bitwarden Firefox extension on the desktop computer i was using, the password was visible and i was able to login.
6. After installing Bitwarden on my desktop computer, the password suddenly appeared on my iPhone.

This is a really, really, REALLY annoying problem and makes me extremely uneasy about using Bitwarden in a work setting (as opposed to personal), as I won't always have time to dick around with it, uninstall the app, re-install, etc, while i'm sitting with clients or trying to log in during a presentation. This bug was reported 6 months ago, i hope Bitwarden are taking it seriously.

**Comment by lumpycustard** [comment]
@chewiesGit what is the point of the refresh animation that triggers when you pull down on the password list if it literally doesn't do anything?

Why doesn't the "pull down" action trigger an actual sync?

What is the pull to refresh action actually doing?

![20190813_134328000_iOS](https://user-images.githubusercontent.com/19260650/62946764-a94ce600-be24-11e9-8605-047f516a2a6f.jpg)

**Comment by kspearrin** [comment]
Pull-down refresh re-loads the list from the local database. It doesn't sync data from the server.

**Comment by paradeiser** [comment]
A forced sync on a pull-down-gesture would help a lot if there are synchronization issues like described above. 
I always have to open settings and force sync when using my iPhone.

**Comment by lumpycustard** [comment]
@kspearrin Thanks for confirming, but what exactly does that achieve? My phone is already displaying the local list, and the local list is missing data stored in my Bitwarden account. 

In other words, if i'm viewing this thread and i get an email advising me that you've replied to me, when i refresh the page, my expectation is that my browser will reach out to git to receive an updated version of that page, as the page my browser is displaying is out of date.

It doesn't make any sense to me that refreshing Bitwarden via the pull down gesture simply reloads the data that i'm already looking at -- however i am a layman and more than likely am completely missing the point.

Either way, i have purchased the pro version of the app and fully support the OSS movement, however this current bug presents a very annoying and (in my view) easily resolvable problem.

**Comment by LapinFou** [comment]
@kspearrin FYI, the issue is still present with the version 2.2.1.
So, the "Fix some sync issues" didn't solve this bug.

**Comment by linpengxuan** [comment]
I actually have the same problem with updated iPhone xs max. Hope there will be a solution to this.

**Comment by ecly** [comment]
Experiencing same issue - iPhone XS

**Comment by csrednicki** [comment]
I have exactly same problem. Push notifications are ON. New passwords added from chrome plugin or web do not sync with mobile app right away. Only when I opened the mobile application for the third time in a row, new passwords were added.

**Comment by EarMaster** [comment]
Same problem here. The sync on Android failed and my new password was even overridden in the web vault after I added the apps url during Autofill. There isn't an entry with password history (because the password wasn't changed yet on my mobile device) and there is no saving of conflicting entries (which is a really bad thing to be honest, because this means I'm now locked out of one of my accounts with no way of getting myself back in).

**Comment by andoma** [comment]
Also got the same problem. I have high hopes for this, but unfortunately this makes it extremely tedious to use.

**Comment by SuzukiStumpy** [comment]
I also have the same issue.  iOS 12.4.1 on an iPhone 7 Plus  ... all notifications are enabled, yet have to manually sync the application whenever a password has been modified via my desktop or laptop (not tried directly editing an item in the web vault yet).  These are generally edited via the browser plugin rather than using the desktop application, so not sure if that's of any relevance or not.

**Comment by jfacevedo** [comment]
Same issue here. iOS 13.1.2 on iPhone XS Max. Bitwarden app version 2.2.5 (59). When I add an item on the website it doesn't show in the iPhone app unless you log out and re-enter what makes it too tedious. Logging out and re-entering might make sense but then why the face-id?

**Comment by guoqiyun** [comment]
Synchronisation has never worked properly on two iOS devices of mine. It seems to be broken on a fundamental level and it always has been. Whenever I make changes, I have to enter the app and manually synchronise from the settings for the changes to appear. Background synchronisation does seem to work to some degree, but it is nowhere near instantaneous.

I cannot reproduce the problem with alternative password managers which also utilise notifications for synchronisation, and yes, both devices permit notifications from Bitwarden.

**Comment by therealgambo** [comment]
I thought I had the same problem, and maybe I do as I haven't fully tried to debug this myself.

One thing I have noticed is that I was expecting the sync to happen when I **unlocked** the app with password/fingerprint, the app was still logged in just locked. Is sync meant to happen during app unlocking, or only when a clean login action is performed?

iOS: 13.1.2
App: 2.2.5

**Comment by chewiesGit** [comment]
@therealgambo Shouldn't changes to the vault that have been made at other sources be pushed to the smartphone app immediately, no matter whether you log in to or unlock the app? This is how I understood it. However, a full forced sync at every login or unlocking would definitely solve the problem for once. 

@kspearrin Just to repeat this again (I mentioned this already in my first post in February): To me this is actually a big security issue. The thing is that when you choose to "Deauthorize all sessions" (in your browser vault), I actually expect that my smartphone vault should be logged out immediately. However, unlocking the app (i.e. with a pin or fingerprint) is still possible since the app did not sync with the vault and didn't notice the deauthorization. Only as soon as you sync manually, the app logs out as it then notices the deauthorization and you have to log in with 2fa. So, for example, when your phone gets stolen and you deauthorize all sessions, your phone is still logged in, which is very problematic I think, as the vault was not deleted from the phone in that scenario!! In my eyes, this problem should therefore get a little more attention, as this is not only a small inconvenience of having to sync manually all the time, but a big security issue. 

Therefore, wouldn't the forced sync at login or unlocking be a quick workaround/solution until we find out what the actual problem is?

**Comment by kspearrin** [comment]
@chewiesGit 

> Therefore, wouldn't the forced sync at login or unlocking be a quick workaround/solution until we find out what the actual problem is?

This is what the app already does. There was a bug in the last version that would cause an issue, however. It should now be resolved in v2.2.6.

**Comment by StrangePeanut** [comment]
I’ve been synchronising my vault manually since I switched to Bitwarden in 2017. If there’s anything I can do to help as an end user, let me know. This issue needs more attention.

**Comment by chewiesGit** [comment]
@kspearrin 

Update came tonight and I just tried it out. Works perfectly! That was very quick! 😄 Thanks a lot!!

**Comment by LapinFou** [comment]
On the French AppStore, the latest available version is still the v2.2.5
Can't wait to test the news v2.2.6 version!

**Comment by thepaulcooper** [comment]
AppStore still showing v2.2.5 for me (in the UK). How long should it be before v2.2.6 shows up?

**Comment by pavankjadda** [comment]
@kspearrin I still see v2.2.5 in AppStore. Hope apple finishes their review soon.

**Comment by LapinFou** [comment]
Maybe the v2.2.6 is only for Android users?
Still no v2.2.6 on the French AppStore. 😢

**Comment by StrangePeanut** [comment]
Remember this update won’t fix the root of the problem. Yes, the vault may sync again upon login, but Bitwarden still won’t background push sync properly like any other password manager does. 😢

**Comment by thepaulcooper** [comment]
I'd like BitWarden to sync every time I foreground the app, not just on login.  Or pull-down to sync.  Or have an explicit sync button on the My Vault screen. Anything, just please don't bury it in Settings.  If auto-syncing is an issue then make it easy to manually sync.

**Comment by StrangePeanut** [comment]
@thepaulcooper Pull-to-sync would be appreciated. No idea why this isn’t already a thing.

Our current options seem to be:

- Settings → Sync → Sync vault now (from within the app)
- Relog (requires version 2.2.6 which isn’t yet available at the time of writing this comment)

**Comment by StrangePeanut** [comment]
@thepaulcooper Pull-to-sync would be appreciated. No idea why this isn’t already a thing.

Our current options seem to be:

- Settings → Sync → Sync vault now (from within the app)
- Relog (requires version 2.2.6 which isn’t yet available at the time of writing this comment)

**Comment by therealgambo** [comment]
@kspearrin still not seeing v2.2.6 on iOS store, surely it doesn't take nearly two months to be approved?

**Comment by Panja0** [comment]
Having the same issue on an iPhone X with iOS 12.1.1
Latest Bitwarden release in the AppStore is v2.2.5

I would really like to ditch my 1Password and use Bitwarden but AutoSync is to important for me.

**Comment by StrangePeanut** [comment]
@Panja0 Well, don’t bother if that’s what you’re waiting for. Synchronisation has never worked properly for me since 2017.

The update they’ve mentioned doesn’t fix it; it merely makes the app sync when **manually** relogging. So, it’s a workaround for all the sync issues if anything.

That said, Bitwarden is still on version 2.2.5 in the UK.

**Comment by Panja0** [comment]
@StrangePeanut 
That's a pity to hear. But thanks for mentioning it!

**Comment by chewiesGit** [comment]
@Panja0 @StrangePeanut 

The app now syncs as soon as you unlock the vault. Unless you never lock your vault (which wouldn't make much sense to me to be honest), this now solves the problem for most of the people here I guess. Sure, it would be better if the changes would be pushed to the app immediately, but the experience is actually not much different now.

**Comment by StrangePeanut** [comment]
@chewiesGit What’s your App Store region? If you look through the comments, you’ll see quite a few users do not have access to the update, and no it doesn’t solve the problem in the slightest:

Users shouldn’t have to open the app and log in to get it to sync when other apps can sync in the background just fine. Keep in mind a full sync on login is unnecessarily taxing on your battery too.

The update which most of us have yet to see provides a workaround and not a fix.

**Comment by chewiesGit** [comment]
@StrangePeanut 
I use android. The update was available there immediately. 

Sure I never said it is an ultimate fix. Just wanted to make sure that it is still improving the situation a lot (at least for me). Battery is not really an argument here. I guess your screen is draining a lot more battery while using your synced passwords :D

**Comment by Panja0** [comment]
On iOS the app is still @ v2.2.5

**Comment by Mart124** [comment]
> I'd like BitWarden to sync every time I foreground the app, not just on login. Or pull-down to sync. Or have an explicit sync button on the My Vault screen. Anything, just please don't bury it in Settings. If auto-syncing is an issue then make it easy to manually sync.

This makes me remember this request, which was for extension :
https://community.bitwarden.com/t/make-sync-now-more-accessible/65
We then have the same issue with mobile app here.

Would really be convenient to have the sync button more accessible, or even better to pull-down to sync.
Or even even better, sync at foreground : we foreground the app, so we of course want an up-to-date vault.

Think about mobile phones with notifications disabled (some users disable them), or self-hosted instances with push disabled...
Also think about shared items / collections, which do not throw notifications...

Syncing at least at foreground time would be a massive improvement.

Many thanks @kspearrin 👍

**Comment by Mart124** [comment]
> > Therefore, wouldn't the forced sync at login or unlocking be a quick workaround/solution until we find out what the actual problem is?
> 
> This is what the app already does. There was a bug in the last version that would cause an issue, however. It should now be resolved in v2.2.6.

> On iOS the app is still @ v2.2.5

Yes I was still experiencing this issue, until I figured this out :)

**Comment by Panja0** [comment]
Any word on an iOS update for Bitwarden? We're still on v.2.2.5 and syncing does not work properly.

**Comment by thepaulcooper** [comment]
Still 2.2.5 in the UK App Store. The last update was three months ago!

**Comment by marcinlesek** [comment]
2.2.5 in Poland still. And this bug still occurs (iPhone 7), unfortunately... 😕

**Comment by Natalie-321** [comment]
Any progress update on this? I'm running iOS 13.3.1 on an iPhone 7, app version 2.2.5 is still the latest version in the US App Store. To confirm, the issue I am having: The vault on my iOS device does not sync changes/additions made to content from my Mac or the Web Vault unless I manually tap the "Sync Vault Now" button in the iOS app. I have deleted and reinstalled the app, and made sure to Allow push notifications. I am hopeful that: 1) The app will automatically start a sync at Bitwarden app launch with the mentioned 2.2.6 update, 2) Whatever bug is causing the app to not sync new content automatically without any intervention (via push notifications presumably) will be resolved soon as well. Thanks for your hard work!

**Comment by StrangePeanut** [comment]
Seems like we’re waiting for a dev to be hired to update the iOS app.

**Comment by thepaulcooper** [comment]
This thread started over a year ago. This does not bode well for the future of BitWarden. Maybe I should consider going back to 1Password.  I don’t want to but if basic issues such as syncing are not resolved quickly then I will lose faith in the long-term viability of this great service.

**Comment by therealgambo** [comment]
> This thread started over a year ago. This does not bode well for the future of BitWarden. Maybe I should consider going back to 1Password. I don’t want to but if basic issues such as syncing are not resolved quickly then I will lose faith in the long-term viability of this great service.

This is the problem with projects that are mostly maintained by a single person. I would understand if the maintainer was inactive, but it seems like he is just actively ignoring this issue and the fact that iOS apps clearly haven't been updated in all regions.

**Comment by kzoran** [comment]
hello everyone,
i found this thread by accident. I've been using BitWarden since December. One of my devices is iphone X with latest IOS, and i have no issues with syncing. it works fine, i even tried to manually to sync under settings and it syncs

**Comment by Panja0** [comment]
Bitwarden v2.3.1 was relased yesterday in the Dutch AppStore.
I really got my hopes up... But the same problem remains! :-(

**Comment by LapinFou** [comment]
Same as @Panja0 version 2.31 release on the French AppStore.
It is a shame that a manual sync as explained here https://github.com/bitwarden/mobile/issues/457#issuecomment-520841886 has not been implemented.
It should be en easy workaround which would make many people happy.

Despite this, BitWarden is still the best password manager on the market. 😄

**Comment by StrangePeanut** [comment]
The v2.3.1 update does not address the problem (UK).

What happened to making the app sync on unlock through the long-promised v2.2.6 update that none of us got?

Is this issue still being worked on? Why is it being actively ignored now?

**Comment by joallard** [comment]
Still experiencing this.

**Comment by joallard** [comment]
This is a major bug on all mobile platforms.

Each time: a login is recent (< 1-2 weeks), "fill with" is invoked on an input,

Logins are empty and main use case for app is broken.

(Reproduced on Android, iPad)

**Comment by benhaynes** [comment]
Same issue here, update a password via the Mac-Chrome extension on my desktop, then try to fill a password via Android App... and it's outdated. I tried locking, etc... nothing seems to automatically or manually sync. This is a very core feature, is there any official response for when this will be resolved?

**Comment by joallard** [comment]
@mportune-bw I see you self-assigned this in March, good to have you on board! Two questions:

- Is this on the schedule for any period?
- Do you have a Steps to reproduce down for the bug? (If not, we might help you get there)

**Comment by mportune-bw** [comment]
@joallard While there's nothing officially scheduled, we keep sync issues under observation because we have such a difficult time reproducing them... which I guess leads me to your second point - if you've discovered a reliable way to reproduce the issue, we're all ears.

**Comment by muzzah** [comment]
Is there a detailed guide on how to setup a dev environment? Im not a VS guy but want to fix this because it is very annoying. It been nearly 2 years and this isnt fixed. I can reproduce it. 
If you can provide some guidance on how to properly setup a dev env here (Im coming across so many diff errors on MacOS and as I said I never used VS/Xamarin for mobile app development) one of the community memebers Im sure can fix it.

**Comment by muzzah** [comment]
@mportune-bw ?

**Comment by cscharf** [comment]
Hi @muzzah , VS for Mac makes it pretty easy to work with Xamarin (since it is basically Xamarin Studio renamed); if you want a full local environment; that's a little more challenging, but you should be able to run the mobile app against production if you feel the issue is somewhere in the mobile app code itself. Xamarin has built in emulators and if you're debugging against Android, it's pretty simple... if you're debugging against iOS, there are many articles on setting up Xcode, an Apple Developer account, registering the appropriate certificates for code signing when running locally, and Xcode has pretty nice support for iOS emulators which VS for Mac supports out of the box.

**Comment by pavankjadda** [comment]
Okay, Now I see different sync issue. Any password updated or deleted in another system/browser is not updating in mobile client autofill. During autofill i still see old/deleted password. This is so annoying lately. Some of my accounts locked out for try trying autofill multiple times with outdated password. 

I tried to manually sync through Pull to refresh and Clicking on Sync button, and i see updated password when I manually search but not during autofill. 

It seems I have to logout and login for the passwords to be in sync at autofill.

**Comment by cscharf** [comment]
@pavankjadda , are you using v2.7.2?

**Comment by pavankjadda** [comment]
Yes 2.7.2(401)

**Comment by thepaulcooper** [comment]
> This thread started over a year ago. This does not bode well for the future of BitWarden. Maybe I should consider going back to 1Password.  I don’t want to but if basic issues such as syncing are not resolved quickly then I will lose faith in the long-term viability of this great service. 

I switched to Strongbox instead.  Very happy now!

**Comment by paradeiser** [comment]
Actually I don't have any sync-issues anymore. Maybe thats why nobody is posting gere lately…

**Comment by LapinFou** [comment]
By the way, with the latest version you can enable the manual sync when sliding the finger from top to bottom.
To enable it, you must go here (not sure of the correct words since it is in French on my smartphone):
**Settings** →  **Synchronization** (in the "_manage_" section) →  Here you got a button to enable this manual sync gesture.

**Comment by chewiesGit** [comment]
I still have sync issues (now on iOS) but the manual sync made it ok for me to deal with it. 

However, and I said that already exactly 2 years ago, the sync issues causes a very problematic security issue in my eyes. Clicking on deauthorizing all session in the online vault will not automatically log out all devices (such as the mobile app, the browser extension or the desktop app) until they finally sync and contact the server. I tried it out recently again. After deauthorizing all sessions in the online vault, I was still able to unlock my desktop app (and browser extension), view all my password and work with the app for several minutes until the app finally logged out since it apparently contacted the server. In case i lose my mobile device, for example, I just cannot feel confident that all sessions were indeed deauthorized as they should due to this issue. Is somebody else experiencing this? Did somebody try that out? Would be curious to know if this is happening to others as well.

Or maybe I should consider Strongbox, too...

**Comment by LapinFou** [comment]
Well, the main security is a very strong master password (with 2FA).
Since, if configured correctly, the Bitwarden vault will be lock after few minutes I don't see where is the problem. 😁
If you got the top security vault in your house but you don't close it before leaving home... For sure, there is a security issue.
BTW, on iOS or Android, Bitwarden is always asking my finger print to auto-fill login credentials.

**Comment by chewiesGit** [comment]
Sure, I know that a securely locked vault is the main security. But why taking the risk? I guess that most people don’t log out every time after using the app, they just lock it, requiring only a finger print or a pin to unlock it. This is the only reason why the deauthorizing function actually exists or was made for. It is supposed to make sure that all devices that are just locked with a pin or finger print (or even unlocked if someone prefers that) get properly logged out. I would just feel much more confident if I knew that all devices are indeed logged out such that the master password as well as 2fa is required to log in, not just a pin or a finger print. I know that there are many risks using a vault like this. But why not eliminating those that we know of and could be eliminated easily. It’s just not very nice to know that a silly bug like this makes the whole thing a bit more unsafe..

**Comment by LapinFou** [comment]
I understand your point. AFIK, this bug is only for iOS and, for sure, must be corrected.
On the other side (to put the thing in perspective), a malicious person should unlock your iPhone, have you finger print or you Pin code before being able to access the Bitwarden vault.
So, again, yes this bug must be fix. However it is not a open hole in the wall. 😉 
Bitwarden, to me, IS the best password manager ever (internet access, plugin for all browser, apps for all platforms). IMHO moving to another solution is not the right move. 😋

**Comment by chewiesGit** [comment]
It at least also exists on MacOS. My iPhone actually syncs much better than the desktop app on my Mac…

Anyway, you are right, it’s not a major security issue. That’s why I am still here after 2 years :) At the same time, I find it a bit frustrating that even after 2 years, nobody seems to take interest in a bug like this. Don’t need to be fixed first thing. But after 2 years?

Well, at the same time I also know myself that deauthorizing wouldn’t have an effect either if somebody just unlocks your vault offline. A real solution to this problem would therefore be when the different apps only work online and show the passwords only after syncing with the server. But that of course is unfeasible as it would mean than one could not view passwords offline.. 

So I guess in case I lose my phone, I should deauthorize all sessions and at the same time change all existing passwords. So even if somebody somehow unlocked the phone offline (which I know is unlikely but it could happen if someone for example watches entering the pin), they would only see an old version of the vault. 

However, that doesn’t mean the sync issue should not be fixed as soon as possible. 😂

**Comment by LapinFou** [comment]
I think the Bitwarden dev team is struggling to reproduce the issue.
For this kind of bug, 80% of the job is to be able to reproduce the problem.

**Comment by mrc77** [comment]
Today I did some testing on this issue, and it seems to happen if there are two or more Bitwarden apps unlocked and sharing the same external IP.

For example, when my Android phone and my Chromebook are both connected to the same WiFi hotspot, the Android app always syncs (maybe because it uses the Google Cloud Messaging instead of web sockets) but the Chrome extension on the Chromebook fails to sync.

If I lock both and switch my phone to use the 4G network (different IP), everything works as expected.

On the other hand, on my Windows PC, where I often unlock the desktop app, the Chrome and the Edge extensions, I rarely see the syncing to work properly.

**Comment by pavankjadda** [comment]
Closing this since I don't see this issue from 2.9.2 version

**Comment by joallard** [comment]
I see this issue in the 2.9.1 version, just reproduced. (iPad)

It seems like 63449a3832478043feb29e2f1a354f6ef4966cc0 is the only change from 2.9.1 to 2.9.2. Did I miss a fix?

**Comment by jeroenbaas** [comment]
Just observed this too in iOS 12 / 2.9.1
Passwords synced only after opening the bitwarden app explicitly.

**Comment by umairatstride** [comment]
We are at iOS 16 and I am experiencing the issue for first in the last three years I have had the service. Of course my subscription is expired. It is being forced by developers?!

**Comment by umairatstride** [comment]
I didn’t realize an open source application existed for a password manager 🤦🏾‍♂️
